#!/usr/bin/env bash
# Harness constraint enforcement — generic CI fallback.
#
# Generated by the harness-engineering plugin.
# Run this script in any CI system to enforce PR-scoped constraints.
#
# Usage: bash ci-generic.sh
#
# Inspired by Birgitta Boeckeler's "Harness Engineering":
# https://martinfowler.com/articles/exploring-gen-ai/harness-engineering.html

set -euo pipefail

if [ ! -f HARNESS.md ]; then
  echo "[harness] No HARNESS.md found — skipping constraint enforcement"
  exit 0
fi

echo "[harness] Checking PR-scoped constraints from HARNESS.md..."

# Placeholder: deterministic tool invocations are added here by
# /harness-constrain as constraints are promoted from unverified to
# deterministic.
#
# Example:
#   echo "[harness] Constraint: Consistent formatting"
#   npx prettier --check "src/**/*.ts"

echo "[harness] All constraints checked. See HARNESS.md for details."
