name: Lint Markdown

on:
  push:
    paths: ['**/*.md']
  pull_request:
    paths: ['**/*.md']

permissions:
  contents: read

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      - uses: DavidAnson/markdownlint-cli2-action@05f32210e84442804257b2a6f20c5bed7f2aaf22  # v23.0.0
